import type { LectureChunk } from "@/lib/types";

/**
 * Seed educational corpus.
 *
 * Every entry here is produced by the same shape the ingestion pipeline emits
 * (parse -> clean -> chapter detection -> concept extraction -> educational
 * chunking -> metadata enrichment). Adding knowledge means adding records to
 * the repository, never touching application code.
 */

type ChunkInput = Omit<LectureChunk, "approval_status" | "batch_id"> &
  Partial<Pick<LectureChunk, "approval_status" | "batch_id">>;

function chunk(input: ChunkInput): LectureChunk {
  return {
    approval_status: "approved",
    batch_id: "aura-2026",
    ...input,
  };
}

export const CORPUS: LectureChunk[] = [
  // ── Physics · Electrostatics (Class 12 · JEE/NEET/Boards) ────────────────
  chunk({
    chunk_id: "phy-42-01",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Electric Potential",
    teacher: "Aman Sir",
    timestamp_start: "01:17:32",
    timestamp_end: "01:19:04",
    text: "Electric potential V at a point is the work done per unit positive charge to bring it from infinity to that point, so V = U/q and its unit is volt. The electric field is not the potential itself — it is how fast the potential changes with distance. Mathematically E = -dV/dr, so the field points in the direction where potential decreases fastest. Agar potential badh raha hai kisi direction mein, electric field usse ulti direction mein point karega.",
    concepts: ["electric potential", "electric field", "potential gradient", "voltage", "V = U/q"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["vector basics", "work energy theorem"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "phy-42-02",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Potential Gradient",
    teacher: "Aman Sir",
    timestamp_start: "01:22:10",
    timestamp_end: "01:24:48",
    text: "Think of potential like the height of a hill and the electric field like the steepness of the slope. Standing high on the hill does not push you — the steepness does. Do jagah same height par ho, to koi slope nahi, matlab field zero. That is why a region can have a large potential but zero electric field: potential constant hai, gradient zero hai.",
    concepts: ["hill analogy", "potential gradient", "equipotential", "electric field", "slope"],
    difficulty: "easy",
    language: "hinglish",
    prerequisites: ["electric potential"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "phy-42-03",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "Boards"],
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Force Direction on a Charge",
    teacher: "Aman Sir",
    timestamp_start: "01:31:05",
    timestamp_end: "01:33:20",
    text: "Force on a charge is F = qE. For a positive charge the force is along the field; for a negative charge it is exactly opposite to the field. Isliye 'force aur field same direction' sirf positive charge ke liye sach hai. The field itself is defined by the force a unit positive test charge would feel, so the sign of the charge flips the direction of the force but never the direction of the field.",
    concepts: ["F = qE", "force direction", "charge sign", "electric field", "vector direction"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["electric field", "vector basics"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "phy-41-01",
    lecture_id: "lec-41",
    lecture_title: "Coulomb's Law",
    lecture_number: 41,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Coulomb's Law",
    teacher: "Aman Sir",
    timestamp_start: "00:24:10",
    timestamp_end: "00:26:40",
    text: "Coulomb's law: F = k q1 q2 / r^2 with k = 9 x 10^9 N m^2 / C^2. The force is along the line joining the two charges, repulsive for like charges and attractive for unlike ones. Distance double karo to force ek-chauthai reh jaata hai, kyunki inverse square law hai.",
    concepts: ["coulomb law", "inverse square", "charge", "force between charges"],
    difficulty: "easy",
    language: "hinglish",
    prerequisites: ["vector basics"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "phy-43-01",
    lecture_id: "lec-43",
    lecture_title: "Potential Difference — Solved Examples",
    lecture_number: 43,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "Boards"],
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Potential Difference",
    teacher: "Aman Sir",
    timestamp_start: "00:41:00",
    timestamp_end: "00:44:15",
    text: "Example: potential varies as V = 4x^2 volts. Then E = -dV/dx = -8x. At x = 2 m the field is -16 V/m, meaning 16 V/m pointing towards decreasing x. Notice the potential at that point is 16 V and the field magnitude is also 16 — same number, completely different physical meaning. Numbers match by coincidence, concept alag hai.",
    concepts: ["potential difference", "E = -dV/dx", "worked example", "potential gradient"],
    difficulty: "hard",
    language: "hinglish",
    prerequisites: ["differentiation", "electric potential"],
    source_type: "solved_example",
  }),
  chunk({
    chunk_id: "phy-44-01",
    lecture_id: "lec-44",
    lecture_title: "Capacitance Basics",
    lecture_number: 44,
    course_id: "physics-12",
    class_level: "Class 12",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Capacitance",
    topic: "Parallel Plate Capacitor",
    teacher: "Aman Sir",
    timestamp_start: "00:12:20",
    timestamp_end: "00:15:02",
    text: "Capacitance C = Q/V measures how much charge a conductor stores per volt. For a parallel plate capacitor C = epsilon0 A / d, so bigger plates or a smaller gap means more capacitance. Energy stored U = 1/2 C V^2. Dielectric daalne se capacitance K guna badh jaata hai.",
    concepts: ["capacitance", "parallel plate", "dielectric", "energy stored", "C = Q/V"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["electric potential", "electric field"],
    source_type: "lecture_transcript",
  }),

  // ── Physics · Laws of Motion & Thermodynamics ────────────────────────────
  chunk({
    chunk_id: "phy-11-01",
    lecture_id: "lec-11",
    lecture_title: "Newton's Laws of Motion",
    lecture_number: 11,
    course_id: "physics-11",
    class_level: "Class 11",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Laws of Motion",
    topic: "Newton's Second Law",
    teacher: "Aman Sir",
    timestamp_start: "00:33:40",
    timestamp_end: "00:36:55",
    text: "Newton's second law says the net external force equals the rate of change of momentum: F = dp/dt, which for constant mass becomes F = ma. Example: a 2 kg block pushed with 10 N on a frictionless floor accelerates at 5 m/s^2. Force alone doesn't decide motion — net force does, so always draw a free body diagram first.",
    concepts: ["newton second law", "F = ma", "momentum", "free body diagram", "acceleration"],
    difficulty: "easy",
    language: "en",
    prerequisites: ["vector basics", "kinematics"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "phy-27-01",
    lecture_id: "lec-27",
    lecture_title: "Thermodynamics — First Law",
    lecture_number: 27,
    course_id: "physics-11",
    class_level: "Class 11",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Physics",
    chapter: "Thermodynamics",
    topic: "First Law of Thermodynamics",
    teacher: "Neha Ma'am",
    timestamp_start: "00:18:05",
    timestamp_end: "00:21:30",
    text: "First law of thermodynamics: dQ = dU + dW. Heat given to a system either raises its internal energy or is spent doing work. In an isothermal process dU = 0 so all heat becomes work; in an adiabatic process dQ = 0 so work is done at the cost of internal energy. Yeh energy conservation ka hi thermodynamic version hai.",
    concepts: [
      "thermodynamics",
      "first law",
      "internal energy",
      "isothermal",
      "adiabatic",
      "heat",
      "work",
    ],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["work energy theorem", "ideal gas"],
    source_type: "lecture_transcript",
  }),

  // ── Mathematics ──────────────────────────────────────────────────────────
  chunk({
    chunk_id: "math-18-01",
    lecture_id: "lec-m18",
    lecture_title: "Integration by Parts",
    lecture_number: 18,
    course_id: "maths-12",
    class_level: "Class 12",
    exams: ["JEE", "Boards", "CUET"],
    subject: "Mathematics",
    chapter: "Integrals",
    topic: "Integration by Parts",
    teacher: "Ritu Ma'am",
    timestamp_start: "00:09:12",
    timestamp_end: "00:13:40",
    text: "Integration by parts comes straight from the product rule of differentiation. Formula: integral of u dv = uv - integral of v du. Choose u by the ILATE order — Inverse, Logarithmic, Algebraic, Trigonometric, Exponential. Example: integral of x e^x dx, take u = x and dv = e^x dx, giving x e^x - e^x + C. Agar product rule clear nahi hai to yeh formula ratna bekaar hai.",
    concepts: [
      "integration by parts",
      "ILATE",
      "product rule",
      "integral",
      "antiderivative",
      "integration",
    ],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["differentiation", "product rule", "basic integration"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "math-04-01",
    lecture_id: "lec-m04",
    lecture_title: "Trigonometric Identities",
    lecture_number: 4,
    course_id: "maths-11",
    class_level: "Class 11",
    exams: ["JEE", "Boards", "CUET"],
    subject: "Mathematics",
    chapter: "Trigonometry",
    topic: "Identities and Ratios",
    teacher: "Ritu Ma'am",
    timestamp_start: "00:21:00",
    timestamp_end: "00:25:10",
    text: "Trigonometry starts from the unit circle: sin is the y coordinate, cos is the x coordinate, tan = sin/cos. The master identity sin^2 x + cos^2 x = 1 is just Pythagoras on that circle. From it, 1 + tan^2 x = sec^2 x and 1 + cot^2 x = cosec^2 x. Compound angle: sin(A+B) = sinA cosB + cosA sinB.",
    concepts: [
      "trigonometry",
      "unit circle",
      "identities",
      "sin cos tan",
      "compound angle",
      "pythagoras",
    ],
    difficulty: "easy",
    language: "en",
    prerequisites: ["geometry basics"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "math-09-01",
    lecture_id: "lec-m09",
    lecture_title: "Differentiation — Product & Chain Rule",
    lecture_number: 9,
    course_id: "maths-12",
    class_level: "Class 12",
    exams: ["JEE", "Boards"],
    subject: "Mathematics",
    chapter: "Derivatives",
    topic: "Product Rule",
    teacher: "Ritu Ma'am",
    timestamp_start: "00:14:30",
    timestamp_end: "00:17:55",
    text: "Product rule: d/dx (u v) = u' v + u v'. Chain rule: d/dx f(g(x)) = f'(g(x)) g'(x). Example: d/dx (x^2 sin x) = 2x sin x + x^2 cos x. Yeh do rules poore calculus ki backbone hain — integration by parts bhi product rule se hi nikalta hai.",
    concepts: ["differentiation", "product rule", "chain rule", "derivative"],
    difficulty: "easy",
    language: "hinglish",
    prerequisites: ["limits", "functions"],
    source_type: "lecture_transcript",
  }),

  // ── Biology ──────────────────────────────────────────────────────────────
  chunk({
    chunk_id: "bio-13-01",
    lecture_id: "lec-b13",
    lecture_title: "Photosynthesis — Light Reaction",
    lecture_number: 13,
    course_id: "biology-11",
    class_level: "Class 11",
    exams: ["NEET", "Boards"],
    subject: "Biology",
    chapter: "Photosynthesis",
    topic: "Light Reaction",
    teacher: "Sneha Ma'am",
    timestamp_start: "00:27:40",
    timestamp_end: "00:31:15",
    text: "The light reaction of photosynthesis takes place in the thylakoid membranes of the chloroplast — specifically in the grana. Photosystem II and Photosystem I sit in that membrane, water is split there (photolysis) releasing oxygen, and ATP and NADPH are produced. Dark reaction ya Calvin cycle stroma mein hota hai, thylakoid mein nahi — yahi sabse common confusion hai.",
    concepts: [
      "photosynthesis",
      "light reaction",
      "thylakoid",
      "grana",
      "chloroplast",
      "photolysis",
      "ATP",
      "NADPH",
    ],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["cell organelles"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "bio-14-01",
    lecture_id: "lec-b14",
    lecture_title: "Calvin Cycle",
    lecture_number: 14,
    course_id: "biology-11",
    class_level: "Class 11",
    exams: ["NEET", "Boards"],
    subject: "Biology",
    chapter: "Photosynthesis",
    topic: "Dark Reaction",
    teacher: "Sneha Ma'am",
    timestamp_start: "00:08:20",
    timestamp_end: "00:11:44",
    text: "The Calvin cycle (dark reaction) happens in the stroma and uses the ATP and NADPH made in the light reaction to fix CO2 into sugar. Three phases: carboxylation by RuBisCO, reduction, and regeneration of RuBP. It is called 'dark' only because it does not need light directly, not because it happens at night.",
    concepts: ["calvin cycle", "dark reaction", "stroma", "RuBisCO", "carbon fixation"],
    difficulty: "medium",
    language: "en",
    prerequisites: ["light reaction"],
    source_type: "lecture_transcript",
  }),

  // ── Chemistry ────────────────────────────────────────────────────────────
  chunk({
    chunk_id: "chem-02-01",
    lecture_id: "lec-c02",
    lecture_title: "Mole Concept",
    lecture_number: 2,
    course_id: "chemistry-11",
    class_level: "Class 11",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Chemistry",
    chapter: "Some Basic Concepts",
    topic: "Mole Concept",
    teacher: "Vikas Sir",
    timestamp_start: "00:16:10",
    timestamp_end: "00:19:50",
    text: "One mole is 6.022 x 10^23 particles — Avogadro's number. Moles = given mass / molar mass = number of particles / 6.022 x 10^23 = volume at STP / 22.4 L for a gas. Mole ek counting unit hai, jaise dozen, bas bahut bada. Molarity M = moles of solute per litre of solution.",
    concepts: ["mole concept", "avogadro number", "molar mass", "molarity", "stoichiometry"],
    difficulty: "easy",
    language: "hinglish",
    prerequisites: ["atomic mass"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "chem-07-01",
    lecture_id: "lec-c07",
    lecture_title: "Periodic Trends",
    lecture_number: 7,
    course_id: "chemistry-11",
    class_level: "Class 11",
    exams: ["JEE", "NEET", "Boards"],
    subject: "Chemistry",
    chapter: "Periodic Table",
    topic: "Periodic Trends",
    teacher: "Vikas Sir",
    timestamp_start: "00:22:05",
    timestamp_end: "00:26:30",
    text: "Across a period, nuclear charge increases while the shell stays the same, so atomic radius decreases and ionisation energy increases. Down a group a new shell is added, so radius increases and ionisation energy falls. Electronegativity follows ionisation energy: fluorine sabse zyada electronegative hai.",
    concepts: [
      "periodic trends",
      "atomic radius",
      "ionisation energy",
      "electronegativity",
      "periodic table",
    ],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["atomic structure"],
    source_type: "lecture_transcript",
  }),

  // ── Computer Science ─────────────────────────────────────────────────────
  chunk({
    chunk_id: "cs-12-01",
    lecture_id: "lec-cs12",
    lecture_title: "Recursion Fundamentals",
    lecture_number: 12,
    course_id: "cs-foundation",
    class_level: "College",
    exams: ["Placements", "Competitive Programming", "Boards"],
    subject: "Computer Science",
    chapter: "Recursion",
    topic: "Base Case",
    teacher: "Rohit Sir",
    timestamp_start: "00:15:44",
    timestamp_end: "00:18:02",
    text: "Every recursive function needs two things: a base case that stops the recursion and a recursive case that moves the problem closer to that base case. Base case nahi hoga to function khud ko infinitely call karta rahega and the call stack overflows. For factorial, the base case is n == 0 returning 1; the recursive case is n * factorial(n - 1).",
    concepts: ["recursion", "base case", "recursive case", "stack overflow", "factorial"],
    difficulty: "easy",
    language: "hinglish",
    prerequisites: ["functions", "call stack"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "cs-12-02",
    lecture_id: "lec-cs12",
    lecture_title: "Recursion Fundamentals",
    lecture_number: 12,
    course_id: "cs-foundation",
    class_level: "College",
    exams: ["Placements", "Competitive Programming"],
    subject: "Computer Science",
    chapter: "Recursion",
    topic: "Call Stack Tracing",
    teacher: "Rohit Sir",
    timestamp_start: "00:24:18",
    timestamp_end: "00:27:05",
    text: "Trace factorial(3) in C++: factorial(3) waits for factorial(2), which waits for factorial(1), which waits for factorial(0). factorial(0) hits the base case and returns 1, then the stack unwinds: 1, 1*1 = 1, 2*1 = 2, 3*2 = 6. Har call apna frame stack par rakhti hai, isliye deep recursion memory bhi kha jaata hai.",
    concepts: ["call stack", "recursion trace", "stack frame", "unwinding", "factorial"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["recursion", "base case"],
    source_type: "lecture_transcript",
  }),
  chunk({
    chunk_id: "cs-19-01",
    lecture_id: "lec-cs19",
    lecture_title: "Time Complexity & Big-O",
    lecture_number: 19,
    course_id: "cs-foundation",
    class_level: "College",
    exams: ["Placements", "Competitive Programming"],
    subject: "Computer Science",
    chapter: "Algorithms",
    topic: "Big-O Notation",
    teacher: "Rohit Sir",
    timestamp_start: "00:06:30",
    timestamp_end: "00:10:12",
    text: "Big-O describes how running time grows with input size, ignoring constants. A single loop over n items is O(n), nested loops are O(n^2), binary search halves the input each step so it is O(log n), and sorting comparison-based is O(n log n). Constants matter in practice but not in the asymptotic class.",
    concepts: ["big o", "time complexity", "binary search", "asymptotic analysis", "algorithms"],
    difficulty: "medium",
    language: "en",
    prerequisites: ["loops", "arrays"],
    source_type: "lecture_transcript",
  }),
];

/** Distinct subjects currently indexed — used for dynamic topic discovery. */
export function indexedSubjects(): string[] {
  return [...new Set(CORPUS.map((c) => c.subject))];
}

/** Topic suggestions for a learner context, straight from the index. */
export function suggestTopics(filter: {
  class_level?: string;
  subjects?: string[];
  goal?: string;
}): { subject: string; chapter: string; topic: string }[] {
  const scored = CORPUS.filter((c) => c.approval_status === "approved").map((c) => {
    let score = 0;
    if (filter.class_level && c.class_level === filter.class_level) score += 3;
    if (filter.subjects?.includes(c.subject)) score += 3;
    if (filter.goal && c.exams.includes(filter.goal)) score += 2;
    return { c, score };
  });
  const seen = new Set<string>();
  return scored
    .sort((a, b) => b.score - a.score)
    .map(({ c }) => ({ subject: c.subject, chapter: c.chapter, topic: c.topic }))
    .filter((t) => {
      const key = `${t.subject}/${t.topic}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, 6);
}
