import type { LectureChunk } from "@/lib/types";

/**
 * Approved course knowledge base (lecture transcripts, notes, solved examples).
 * In production this is served from the vector repository; the shape and
 * metadata here match exactly what the retriever expects from that backend.
 */
export const CORPUS: LectureChunk[] = [
  {
    chunk_id: "phy-42-01",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Electrostatics",
    teacher: "Aman Sir",
    timestamp_start: "01:17:32",
    timestamp_end: "01:19:04",
    text: "Electric potential V at a point is the work done per unit positive charge to bring it from infinity to that point, so V = U/q and its unit is volt. The electric field is not the potential itself — it is how fast the potential changes with distance. Mathematically E = -dV/dr, so the field points in the direction where potential decreases fastest. Agar potential badh raha hai kisi direction mein, electric field usse ulti direction mein point karega.",
    concepts: ["electric potential", "electric field", "potential gradient", "V = U/q"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["vector basics", "work energy theorem"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "phy-42-02",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Electrostatics",
    teacher: "Aman Sir",
    timestamp_start: "01:22:10",
    timestamp_end: "01:24:48",
    text: "Think of potential like height on a hill and the electric field like the slope of that hill. A ball placed on a steep slope accelerates more; similarly a charge in a region with a steep potential gradient feels a stronger field. Flat region means equal potential — an equipotential surface — and there the component of the field along the surface is zero.",
    concepts: ["potential gradient", "equipotential surface", "analogy", "electric field"],
    difficulty: "easy",
    language: "en",
    prerequisites: ["vector basics"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "phy-42-03",
    lecture_id: "lec-42",
    lecture_title: "Electric Potential & Electric Field",
    lecture_number: 42,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Electrostatics",
    teacher: "Aman Sir",
    timestamp_start: "01:31:05",
    timestamp_end: "01:33:20",
    text: "Students often mix up potential V and potential energy U. Potential is a property of the field at a point and does not depend on the test charge; potential energy depends on the charge you place there, U = qV. Similarly the field E is a vector while potential V is a scalar — you can add potentials arithmetically but fields must be added as vectors.",
    concepts: [
      "potential energy",
      "electric potential",
      "scalar vs vector",
      "potential vs potential energy",
    ],
    difficulty: "medium",
    language: "en",
    prerequisites: ["vector basics"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "phy-41-01",
    lecture_id: "lec-41",
    lecture_title: "Coulomb's Law & Electric Field of a Point Charge",
    lecture_number: 41,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Electrostatics",
    teacher: "Aman Sir",
    timestamp_start: "00:41:12",
    timestamp_end: "00:43:50",
    text: "For a point charge q, the electric field magnitude at distance r is E = kq/r^2 and the potential is V = kq/r. Notice the field falls as 1/r^2 while potential falls as 1/r. Force on a test charge is F = qE, and the direction of the force on a negative charge is opposite to the field direction.",
    concepts: ["coulomb law", "electric field", "point charge", "force on charge"],
    difficulty: "easy",
    language: "en",
    prerequisites: ["vector basics"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "phy-43-01",
    lecture_id: "lec-43",
    lecture_title: "Solved Examples — Potential and Field",
    lecture_number: 43,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Electrostatics",
    teacher: "Aman Sir",
    timestamp_start: "00:12:00",
    timestamp_end: "00:15:30",
    text: "Example: potential in a region varies as V = 3x^2 volts. Find the field at x = 2 m. Using E = -dV/dx we get E = -6x, so at x = 2 the field is -12 V/m, meaning 12 V/m directed along the negative x axis. Always take the negative gradient — forgetting the minus sign is the most common mistake in exams.",
    concepts: ["potential gradient", "E = -dV/dr", "solved example"],
    difficulty: "hard",
    language: "en",
    prerequisites: ["differentiation", "vector basics"],
    source_type: "solved_example",
    approval_status: "approved",
  },
  {
    chunk_id: "phy-44-01",
    lecture_id: "lec-44",
    lecture_title: "Capacitance Basics",
    lecture_number: 44,
    course_id: "physics-11",
    batch_id: "arjuna-2026",
    subject: "Physics",
    chapter: "Capacitance",
    teacher: "Aman Sir",
    timestamp_start: "00:05:40",
    timestamp_end: "00:08:10",
    text: "Capacitance C = Q/V measures how much charge a conductor stores per volt of potential. For a parallel plate capacitor C = e0*A/d. The field between the plates is uniform and equals V/d.",
    concepts: ["capacitance", "parallel plate", "uniform field"],
    difficulty: "medium",
    language: "en",
    prerequisites: ["electric potential"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "cs-12-01",
    lecture_id: "lec-12",
    lecture_title: "Recursion — Base Case and Recursive Case",
    lecture_number: 12,
    course_id: "cs-foundation",
    batch_id: "arjuna-2026",
    subject: "Programming",
    chapter: "Recursion",
    teacher: "Neha Ma'am",
    timestamp_start: "00:22:14",
    timestamp_end: "00:25:02",
    text: "Every recursive function needs two things: a base case that stops the recursion and a recursive case that moves the input closer to that base case. Agar base case missing hai ya kabhi hit hi nahi hota, function baar baar khud ko call karta rahega aur stack overflow ho jayega. Return value ko bhi propagate karna padta hai — recursive call ka result return nahi kiya to answer kho jata hai.",
    concepts: ["recursion", "base case", "stack overflow", "return propagation"],
    difficulty: "medium",
    language: "hinglish",
    prerequisites: ["control flow", "functions"],
    source_type: "lecture_transcript",
    approval_status: "approved",
  },
  {
    chunk_id: "cs-12-02",
    lecture_id: "lec-12",
    lecture_title: "Recursion — Base Case and Recursive Case",
    lecture_number: 12,
    course_id: "cs-foundation",
    batch_id: "arjuna-2026",
    subject: "Programming",
    chapter: "Recursion",
    teacher: "Neha Ma'am",
    timestamp_start: "00:31:40",
    timestamp_end: "00:34:05",
    text: "Trace factorial(3): it calls factorial(2), which calls factorial(1), which hits the base case n == 1 and returns 1. Each frame then multiplies and returns upward. Drawing the call stack on paper is the fastest way to debug a recursion that never terminates.",
    concepts: ["recursion", "call stack", "factorial", "tracing"],
    difficulty: "easy",
    language: "en",
    prerequisites: ["control flow"],
    source_type: "solved_example",
    approval_status: "approved",
  },
];
